version: '3'
services:
  app:
    container_name: slack-request-app
    env_file: slack-request.env
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: slack-request-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"